# Generated by Django 5.2.1 on 2025-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the trainer is verified by admin'),
        ),
    ]
