# Generated by Django 5.2.1 on 2025-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_resourcecategory_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersubscription',
            options={'verbose_name': 'Customer Subscription', 'verbose_name_plural': 'Customer Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='customersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='customersubscription',
            table='customer_subscriptions',
        ),
    ]
